# -*- coding: utf-8 -*-
"""Sam_ai_task_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15giztkNEYPQAfNxEQ2G6y4Usq89ZWNQ3
"""

import pandas as pd
import numpy as np
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# --- 1. Dataset Setup ---
def load_data():
    """Loads the SMS Spam Collection dataset from a public URL."""
    url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
    # The dataset is tab-separated with columns: label, message
    df = pd.read_csv(url, sep='\t', header=None, names=['label', 'message'])
    return df

# --- 2. Text Preprocessing (NLP) ---
nltk.download('stopwords', quiet=True)
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess_text(text):
    """Cleans raw text: lowercase, removes HTML/URLs, punctuation, stopwords, and applies stemming."""
    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Tokenize, remove stopwords, and stem
    words = text.split()
    cleaned_words = [stemmer.stem(w) for w in words if w not in stop_words]
    return " ".join(cleaned_words)

# --- 3 & 4. Feature Extraction & Model Training ---
def train_spam_classifier(df):
    # Preprocess the message column
    df['processed_message'] = df['message'].apply(preprocess_text)

    # Map labels to binary values
    df['label_num'] = df['label'].map({'ham': 0, 'spam': 1})

    # Split data (Stratified 80/20 split)
    X_train, X_test, y_train, y_test = train_test_split(
        df['processed_message'],
        df['label_num'],
        test_size=0.20,
        random_state=42,
        stratify=df['label_num']
    )

    # TF-IDF Vectorization
    tfidf = TfidfVectorizer(max_features=5000)
    X_train_tfidf = tfidf.fit_transform(X_train)
    X_test_tfidf = tfidf.transform(X_test)

    # Initialize and train Multinomial Naive Bayes
    model = MultinomialNB()
    model.fit(X_train_tfidf, y_train)

    return model, tfidf, X_test_tfidf, y_test

# --- 5. Evaluation & Deployment ---
def evaluate_model(model, X_test_tfidf, y_test):
    y_pred = model.predict(X_test_tfidf)
    print("--- Model Evaluation ---")
    print(f"Accuracy:  {accuracy_score(y_test, y_pred):.4f}")
    print(f"Precision: {precision_score(y_test, y_pred):.4f}")
    print(f"Recall:    {recall_score(y_test, y_pred):.4f}")
    print(f"F1-Score:  {f1_score(y_test, y_pred):.4f}")
    print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=['HAM', 'SPAM']))

def predict_email(text, model, tfidf):
    """Inference function to classify raw email strings."""
    processed = preprocess_text(text)
    vectorized = tfidf.transform([processed])
    prediction = model.predict(vectorized)[0]
    label = "SPAM" if prediction == 1 else "HAM/LEGITIMATE"
    print(f"Input Text: {text[:80]}...")
    print(f"Prediction: {label}\n")

# Execution Flow
if __name__ == "__main__":
    # Load and Train
    data = load_data()
    clf_model, vectorizer, X_test_vec, y_test_labels = train_spam_classifier(data)

    # Evaluate
    evaluate_model(clf_model, X_test_vec, y_test_labels)

    # Demo Inference
    print("--- Sample Predictions ---")
    predict_email("Congratulations! You've won a $1,000 Walmart gift card. Click here to claim now!", clf_model, vectorizer)
    predict_email("Hey, are we still meeting for lunch at 12:30 today? Let me know.", clf_model, vectorizer)
    predict_email("URGENT: Your account has been compromised. Log in at http://bit.ly/fake-link to secure it.", clf_model, vectorizer)